### ISSUE TITLE
Some test cases and improvements

### ISSUE THREAD

**Issue by lapets** [lapets/pydrogen#1]
Create a few working examples demonstrating how the  library can be used to predict running times for a small subset of Python programs, including:
- explicit (i.e., numeric) prediction of steps the number of steps;
- symbolic prediction (i.e., as a polynomial) for functions that take a list of integers.

Identify any issues that arise from the use of the library (and add tickets as necessary).

**Comment by timql** [comment]
8153a687c79d913cb67bfb3bcbb32e13ca343b20 has a basic implementation of running time predictors for both symbolic and explicit prediction -- the explicit prediction is largely identical to what was in the examples. Sympy has a nice big-O class that I'm making use of; both are largely untested. As I code up more examples I'll add the necessary implementations to enable analysis of more complicated functions.
